[package]
name = "shared-crypto"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
eyre = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
fastcrypto.workspace = true

bcs = { workspace = true }
