[package]
name = "starcoin-bridge-authority-aggregation"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
# Stub for Starcoin bridge
log = { workspace = true }
tokio = { workspace = true }
futures = "0.3"
