[package]
name = "Stc-Bridge-Move"
version = "0.0.1"

[addresses]
StarcoinFramework = "0x1"
std = "0x1"
Bridge = "0xba0f421cab925857ae31f058c2f027f8"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "v12" }

[dev-dependencies]
UnitTest = { git = "https://github.com/starcoinorg/starcoin-framework.git", subdir = "unit-test", rev = "v12" }